### ISSUE TITLE
Playing UPnP to Argon Radio 2i - and the song is kind of stuck on the last second...

### ISSUE THREAD

**Issue by larhedse** [philippe44/LMS-to-uPnP#85]
I might be wrong here, but I still need to figure this one out...

I have LMS 8.5.2 with a brand new (to me, installed a few hours ago) UPnP/DLNA bridge (v.3.3.9).

When I play a playlist, well it is an album but anyway, it get's stuck on the last second on a few songs - and it just stands there (and of course the Argon Radio is dead silent), jumping back -1 second and then play 1 second, and all over again. I have to use UPnP to play/control the Argon Radio 2i, since well it has no interface native to LMS ;-)

So what am I doing wrong here? How come I get this behavior? What am I missing?

**Comment by philippe44** [comment]
Welcome to the beautiful land of UPnP where everybody is free to do whatever they want and not. Imply to the standard, in addition of immensely buggy implementations. My advice in your case is to remove the gapless option

**Comment by larhedse** [comment]
Nope - that did not fix my challenge - any more tips?

(and yes, I restarted LMS before testing)

**Comment by philippe44** [comment]
Then I suggest you go the LMS forum. I've been discussing options many times and others also can share their experience. Also, the user manual contains a fair bit of explanation wrt that issue

**Comment by larhedse** [comment]
For anyone else that may or may not stumble onto a challenge like i have, and have a Home Assistant system integrated into/with LMS: create a automation that checks the duration and position of the played song, and execute next track if needed. I got this tip after browsing the LMS forum and found a few threads about the same challenge, however those were for Spotty I think. Or just use the code I have included in this message:
```

alias: Media - Sovrum - Argon - Next Song when stuck...
description: ""
triggers:
  - trigger: time_pattern
    seconds: "15"
conditions:
  - condition: template
    value_template: >-
      {% if ( (states('media_player.argon_radio_2i_0022618be138_3') ==
      'playing') and
          (state_attr('media_player.argon_radio_2i_0022618be138_3', 'media_duration')|int(0) > 1) and 
          (state_attr('media_player.argon_radio_2i_0022618be138_3', 'media_duration')|int(0) - 
           state_attr('media_player.argon_radio_2i_0022618be138_3', 'media_position')|int(10) <= 1) ) %} true
      {% endif%}
actions:
  - action: media_player.media_next_track
    metadata: {}
    data: {}
    target:
      entity_id: media_player.argon_radio_2i_0022618be138_3
mode: single
```
